### PR TITLE
Optimize the way of packaging with maven-shade-plugin

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Comment by zuston** [comment]
@maobaolong Please check it. Thanks

**Comment by maobaolong** [comment]
@captainzmc Could you please take a look at this PR?

**Comment by captainzmc** [comment]
Thanks for @zuston 's contribution. When I tested this patch, I found that there were many warnings. Can you confirm whether these warnings will affect the final jar? 

In addition, the naming convention for packages under target has also changed:
hcfsfuse-1.0.0-SNAPSHOT-jar-with-dependencies.jar -> hcfsfuse-1.0.0-SNAPSHOT.jar
hcfsfuse-1.0.0-SNAPSHOT.jar -> original-hcfsfuse-1.0.0-SNAPSHOT.jar
Can this be restored to the original naming convention?

**Comment by zuston** [comment]
Thanks for your review @captainzmc. I will check the warning.

Naming convention may be difficult because of the restriction of the maven-shade-plugin. Besides i think it's unnecessary to be restored it's origin name, any details on it?

**Comment by captainzmc** [comment]
> Naming convention may be difficult because of the restriction of the maven-shade-plugin. Besides i think it's unnecessary to be restored it's origin name, any details on it?

The naming convention for jar-with-dependencies is common across many projects, and makes it easier for users to distinguish between them. The maven-shade-plugin can also change the naming rules of the JAR using <finalName>. You can refer to the [implementation of Alluxio](https://github.com/Alluxio/alluxio/blob/723b4a26ece8c7458409ced194e5e30f2c42070f/assembly/server/pom.xml#L84).

**Comment by zuston** [comment]
> > Naming convention may be difficult because of the restriction of the maven-shade-plugin. Besides i think it's unnecessary to be restored it's origin name, any details on it?
> 
> The naming convention for jar-with-dependencies is common across many projects, and makes it easier for users to distinguish between them. The maven-shade-plugin can also change the naming rules of the JAR using . You can refer to the [implementation of Alluxio](https://github.com/Alluxio/alluxio/blob/723b4a26ece8c7458409ced194e5e30f2c42070f/assembly/server/pom.xml#L84).

The warning looks harmless, and everything is well when mounting HDFS.

The naming convention has been done. @captainzmc

**Comment by maobaolong** [comment]
@zuston It looks like your email didn't bind to your github account from the commit information, please fix it, thank you.

**Comment by zuston** [comment]
@maobaolong Done

**Review by maobaolong — APPROVED** [review]
@captainzmc Would you like to take another look?

**Review by captainzmc — APPROVED** [review]
+1 Looks good. thanks @zuston‘s patch.

**Pull request merged**
